# Generated by Django 4.2.7 on 2023-12-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='bestSeller',
            field=models.BooleanField(default=False),
        ),
    ]
